# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'runpopup.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RunOptionsDialog(object):
    def setupUi(self, RunOptionsDialog):
        RunOptionsDialog.setObjectName("RunOptionsDialog")
        RunOptionsDialog.resize(400, 300)

        self.mainVerticalLayout = QtWidgets.QVBoxLayout(RunOptionsDialog)
        self.mainVerticalLayout.setObjectName("mainVerticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBoxType = QtWidgets.QGroupBox(RunOptionsDialog)
        self.groupBoxType.setObjectName("groupBoxType")
        self.verticalLayoutType = QtWidgets.QVBoxLayout(self.groupBoxType)
        self.verticalLayoutType.setObjectName("verticalLayoutType")
        self.radioButtonSteps = QtWidgets.QRadioButton(self.groupBoxType)
        self.radioButtonSteps.setObjectName("radioButtonSteps")
        self.verticalLayoutType.addWidget(self.radioButtonSteps)
        self.radioButtonFiles = QtWidgets.QRadioButton(self.groupBoxType)
        self.radioButtonFiles.setObjectName("radioButtonFiles")
        self.verticalLayoutType.addWidget(self.radioButtonFiles)
        self.radioButtonIndefinite = QtWidgets.QRadioButton(self.groupBoxType)
        self.radioButtonIndefinite.setObjectName("radioButtonIndefinite")
        self.verticalLayoutType.addWidget(self.radioButtonIndefinite)
        self.horizontalLayout.addWidget(self.groupBoxType)
        self.groupBoxFiles = QtWidgets.QGroupBox(RunOptionsDialog)
        self.groupBoxFiles.setObjectName("groupBoxFiles")
        self.verticalLayoutFiles = QtWidgets.QVBoxLayout(self.groupBoxFiles)
        self.verticalLayoutFiles.setSpacing(6)
        self.verticalLayoutFiles.setObjectName("verticalLayoutFiles")
        self.checkBoxAllFiles = QtWidgets.QCheckBox(self.groupBoxFiles)
        self.checkBoxAllFiles.setObjectName("checkBoxAllFiles")
        self.verticalLayoutFiles.addWidget(self.checkBoxAllFiles)
        self.fileListWidget = QtWidgets.QListWidget(self.groupBoxFiles)
        self.fileListWidget.setObjectName("fileListWidget")
        self.verticalLayoutFiles.addWidget(self.fileListWidget)
        self.horizontalLayout.addWidget(self.groupBoxFiles)
        self.mainVerticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayoutOffset = QtWidgets.QHBoxLayout()
        self.horizontalLayoutOffset.setObjectName("horizontalLayoutOffset")
        self.labelOffset = QtWidgets.QLabel(RunOptionsDialog)
        self.labelOffset.setObjectName("labelOffset")
        self.horizontalLayoutOffset.addWidget(self.labelOffset)
        self.lineEditOffset = QtWidgets.QLineEdit(RunOptionsDialog)
        self.lineEditOffset.setObjectName("lineEditOffset")
        self.horizontalLayoutOffset.addWidget(self.lineEditOffset)
        self.labelStepCount = QtWidgets.QLabel(RunOptionsDialog)
        self.labelStepCount.setObjectName("labelStepCount")
        self.horizontalLayoutOffset.addWidget(self.labelStepCount)
        self.lineEditStepCount = QtWidgets.QLineEdit(RunOptionsDialog)
        self.lineEditStepCount.setObjectName("lineEditStepCount")
        self.horizontalLayoutOffset.addWidget(self.lineEditStepCount)
        self.mainVerticalLayout.addLayout(self.horizontalLayoutOffset)
        self.horizontalLayoutButtons = QtWidgets.QHBoxLayout()
        self.horizontalLayoutButtons.setObjectName("horizontalLayoutButtons")
        self.pushButtonStart = QtWidgets.QPushButton(RunOptionsDialog)
        self.pushButtonStart.setObjectName("pushButtonStart")
        self.horizontalLayoutButtons.addWidget(self.pushButtonStart)
        self.pushButtonCancel = QtWidgets.QPushButton(RunOptionsDialog)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayoutButtons.addWidget(self.pushButtonCancel)
        self.mainVerticalLayout.addLayout(self.horizontalLayoutButtons)

        self.retranslateUi(RunOptionsDialog)
        QtCore.QMetaObject.connectSlotsByName(RunOptionsDialog)

    def retranslateUi(self, RunOptionsDialog):
        _translate = QtCore.QCoreApplication.translate
        RunOptionsDialog.setWindowTitle(_translate("RunOptionsDialog", "Run Options"))
        self.groupBoxType.setTitle(_translate("RunOptionsDialog", "Type"))
        self.radioButtonSteps.setText(_translate("RunOptionsDialog", "Steps"))
        self.radioButtonFiles.setText(_translate("RunOptionsDialog", "Files"))
        self.radioButtonIndefinite.setText(_translate("RunOptionsDialog", "Indefinite"))
        self.groupBoxFiles.setTitle(_translate("RunOptionsDialog", "Select File(s)"))
        self.checkBoxAllFiles.setText(_translate("RunOptionsDialog", "All Files"))
        self.labelOffset.setText(_translate("RunOptionsDialog", "Offset:"))
        self.labelStepCount.setText(_translate("RunOptionsDialog", "Step count:"))
        self.pushButtonStart.setText(_translate("RunOptionsDialog", "Start"))
        self.pushButtonCancel.setText(_translate("RunOptionsDialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RunOptionsDialog = QtWidgets.QDialog()
    ui = Ui_RunOptionsDialog()
    ui.setupUi(RunOptionsDialog)
    RunOptionsDialog.show()
    sys.exit(app.exec_())
